### ISSUE TITLE
How does this even work?

### ISSUE THREAD

**Issue by MajorSquiggles** [Caraxi/MacroRecursion#1]
I've tried absolutely everything I can think of to try and get this to work in game and either I'm being really dumb or something isn't being explained. What is the actual syntax for this plugin and how do I get it to work?

**Comment by knockDOUGH** [comment]
use `/runmacro [##]` in your macros. `[##]` is the macro number bottom left of macro UI. or you can just use `/runmacro [##]` in the chat log as well.

**Comment by MajorSquiggles** [comment]
Thank you. It was driving me crazy. The description has [individual|shared] [line] so I thought I needed to specify the category.
