### ISSUE TITLE
New change breaks previously designed macros

### ISSUE THREAD

**Issue by ghost** [Caraxi/MacroRecursion#2]
My macro menu is structured with the second macro in a chain directly *below* the macro that triggers it.
The change that prohibits using /runmacro inside a macro makes it so I will have to completely restructure how my macros are arranged.

**Comment by akaNaymin** [comment]
The functionality is actually there, author just forgot to add it to the help message.
Replacing the line you previously used with `/nextmacro down` should work

**Comment by ghost** [comment]
Interesting. I'll test that, and if it works, I'll go ahead and close this issue.

**Comment by ghost** [comment]
Confirmed.

Help text could use an update, but this issue as it was posted is not present.
